# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f40ad526478302ca92a4f19ca8abcf10"
name = "wishlist-app"
application_url = "https://obituaries-waters-electrical-informed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-devs.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://obituaries-waters-electrical-informed.trycloudflare.com/auth/callback",
  "https://obituaries-waters-electrical-informed.trycloudflare.com/auth/shopify/callback",
  "https://obituaries-waters-electrical-informed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
